- name: install a Apache on Dev
    apt:
      name: apache2
      state: latest
      when: ansible_distribution == 'Ubuntu'

- name: start the service
    service:
      name: apache2
      state: started
      when: ansible_distribution == 'Ubuntu'
	  
- name: copy the content of the web site
  copy: src=index1.html  dest="/var/www/html/"
